// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eth/v1alpha1/node.proto

package eth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SyncStatus struct {
	Syncing              bool     `protobuf:"varint,1,opt,name=syncing,proto3" json:"syncing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncStatus) Reset()         { *m = SyncStatus{} }
func (m *SyncStatus) String() string { return proto.CompactTextString(m) }
func (*SyncStatus) ProtoMessage()    {}
func (*SyncStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d5c81e0a630f5ab, []int{0}
}

func (m *SyncStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncStatus.Unmarshal(m, b)
}
func (m *SyncStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncStatus.Marshal(b, m, deterministic)
}
func (m *SyncStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncStatus.Merge(m, src)
}
func (m *SyncStatus) XXX_Size() int {
	return xxx_messageInfo_SyncStatus.Size(m)
}
func (m *SyncStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SyncStatus proto.InternalMessageInfo

func (m *SyncStatus) GetSyncing() bool {
	if m != nil {
		return m.Syncing
	}
	return false
}

type Genesis struct {
	GenesisTime            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=genesis_time,json=genesisTime,proto3" json:"genesis_time,omitempty"`
	DepositContractAddress []byte               `protobuf:"bytes,2,opt,name=deposit_contract_address,json=depositContractAddress,proto3" json:"deposit_contract_address,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}             `json:"-"`
	XXX_unrecognized       []byte               `json:"-"`
	XXX_sizecache          int32                `json:"-"`
}

func (m *Genesis) Reset()         { *m = Genesis{} }
func (m *Genesis) String() string { return proto.CompactTextString(m) }
func (*Genesis) ProtoMessage()    {}
func (*Genesis) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d5c81e0a630f5ab, []int{1}
}

func (m *Genesis) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Genesis.Unmarshal(m, b)
}
func (m *Genesis) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Genesis.Marshal(b, m, deterministic)
}
func (m *Genesis) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Genesis.Merge(m, src)
}
func (m *Genesis) XXX_Size() int {
	return xxx_messageInfo_Genesis.Size(m)
}
func (m *Genesis) XXX_DiscardUnknown() {
	xxx_messageInfo_Genesis.DiscardUnknown(m)
}

var xxx_messageInfo_Genesis proto.InternalMessageInfo

func (m *Genesis) GetGenesisTime() *timestamp.Timestamp {
	if m != nil {
		return m.GenesisTime
	}
	return nil
}

func (m *Genesis) GetDepositContractAddress() []byte {
	if m != nil {
		return m.DepositContractAddress
	}
	return nil
}

type Version struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Metadata             string   `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d5c81e0a630f5ab, []int{2}
}

func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (m *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(m, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Version) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

type ImplementedServices struct {
	Services             []string `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImplementedServices) Reset()         { *m = ImplementedServices{} }
func (m *ImplementedServices) String() string { return proto.CompactTextString(m) }
func (*ImplementedServices) ProtoMessage()    {}
func (*ImplementedServices) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d5c81e0a630f5ab, []int{3}
}

func (m *ImplementedServices) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImplementedServices.Unmarshal(m, b)
}
func (m *ImplementedServices) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImplementedServices.Marshal(b, m, deterministic)
}
func (m *ImplementedServices) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImplementedServices.Merge(m, src)
}
func (m *ImplementedServices) XXX_Size() int {
	return xxx_messageInfo_ImplementedServices.Size(m)
}
func (m *ImplementedServices) XXX_DiscardUnknown() {
	xxx_messageInfo_ImplementedServices.DiscardUnknown(m)
}

var xxx_messageInfo_ImplementedServices proto.InternalMessageInfo

func (m *ImplementedServices) GetServices() []string {
	if m != nil {
		return m.Services
	}
	return nil
}

func init() {
	proto.RegisterType((*SyncStatus)(nil), "ethereum.eth.v1alpha1.SyncStatus")
	proto.RegisterType((*Genesis)(nil), "ethereum.eth.v1alpha1.Genesis")
	proto.RegisterType((*Version)(nil), "ethereum.eth.v1alpha1.Version")
	proto.RegisterType((*ImplementedServices)(nil), "ethereum.eth.v1alpha1.ImplementedServices")
}

func init() { proto.RegisterFile("eth/v1alpha1/node.proto", fileDescriptor_4d5c81e0a630f5ab) }

var fileDescriptor_4d5c81e0a630f5ab = []byte{
	// 488 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xdf, 0x6a, 0x13, 0x41,
	0x14, 0xc6, 0xd9, 0x54, 0x4c, 0x33, 0xad, 0x37, 0x2b, 0x6d, 0xe3, 0xb6, 0x6a, 0x5c, 0x41, 0x8a,
	0x17, 0x33, 0xa4, 0x82, 0x08, 0x22, 0x62, 0x25, 0x04, 0x41, 0xa4, 0x6c, 0xc4, 0x0b, 0x29, 0x84,
	0xc9, 0xee, 0x71, 0x77, 0x20, 0xf3, 0x87, 0x9d, 0x93, 0x40, 0x6e, 0xf3, 0x04, 0x82, 0x6f, 0xe1,
	0xa3, 0x78, 0xe3, 0x85, 0xaf, 0xe0, 0x83, 0xc8, 0xee, 0xce, 0xd8, 0x6a, 0x37, 0x85, 0xde, 0xcd,
	0x99, 0x73, 0xbe, 0xef, 0x37, 0xfb, 0x9d, 0x25, 0x07, 0x80, 0x05, 0x5b, 0x0e, 0xf9, 0xdc, 0x14,
	0x7c, 0xc8, 0x94, 0xce, 0x80, 0x9a, 0x52, 0xa3, 0x0e, 0xf7, 0x00, 0x0b, 0x28, 0x61, 0x21, 0x29,
	0x60, 0x41, 0xfd, 0x44, 0x74, 0x94, 0x6b, 0x9d, 0xcf, 0x81, 0x71, 0x23, 0x18, 0x57, 0x4a, 0x23,
	0x47, 0xa1, 0x95, 0x6d, 0x44, 0xd1, 0xa1, 0xeb, 0xd6, 0xd5, 0x6c, 0xf1, 0x85, 0x81, 0x34, 0xb8,
	0x72, 0xcd, 0x87, 0xff, 0x37, 0x51, 0x48, 0xb0, 0xc8, 0xa5, 0x69, 0x06, 0xe2, 0x27, 0x84, 0x4c,
	0x56, 0x2a, 0x9d, 0x20, 0xc7, 0x85, 0x0d, 0xfb, 0xa4, 0x6b, 0x57, 0x2a, 0x15, 0x2a, 0xef, 0x07,
	0x83, 0xe0, 0x78, 0x3b, 0xf1, 0x65, 0xbc, 0x0e, 0x48, 0x77, 0x0c, 0x0a, 0xac, 0xb0, 0xe1, 0x2b,
	0xb2, 0x9b, 0x37, 0xc7, 0x69, 0x65, 0x57, 0x8f, 0xee, 0x9c, 0x44, 0xb4, 0x61, 0x51, 0xcf, 0xa2,
	0x1f, 0x3d, 0x2b, 0xd9, 0x71, 0xf3, 0xd5, 0x4d, 0xf8, 0x82, 0xf4, 0x33, 0x30, 0xda, 0x0a, 0x9c,
	0xa6, 0x5a, 0x61, 0xc9, 0x53, 0x9c, 0xf2, 0x2c, 0x2b, 0xc1, 0xda, 0x7e, 0x67, 0x10, 0x1c, 0xef,
	0x26, 0xfb, 0xae, 0xff, 0xd6, 0xb5, 0xdf, 0x34, 0xdd, 0xf8, 0x35, 0xe9, 0x7e, 0x82, 0xd2, 0x0a,
	0xad, 0xaa, 0x97, 0x2e, 0x9b, 0x63, 0x8d, 0xef, 0x25, 0xbe, 0x0c, 0x23, 0xb2, 0x2d, 0x01, 0x79,
	0xc6, 0x91, 0xd7, 0x76, 0xbd, 0xe4, 0x6f, 0x1d, 0x0f, 0xc9, 0xdd, 0x77, 0xd2, 0xcc, 0x41, 0x82,
	0x42, 0xc8, 0x26, 0x50, 0x2e, 0x45, 0x0a, 0xb6, 0x92, 0x58, 0x77, 0xee, 0x07, 0x83, 0xad, 0x4a,
	0xe2, 0xeb, 0x93, 0x9f, 0x5b, 0xe4, 0xd6, 0x07, 0x9d, 0x41, 0xa8, 0xc8, 0x9d, 0x31, 0xe0, 0xa5,
	0xb0, 0xf6, 0xaf, 0x7c, 0xf0, 0xa8, 0x4a, 0x3e, 0x7a, 0x44, 0x5b, 0xd7, 0x48, 0x2f, 0xa4, 0x71,
	0xbc, 0xfe, 0xf5, 0xfb, 0x5b, 0xe7, 0x28, 0x8c, 0xd8, 0x95, 0x5f, 0x81, 0xb9, 0xc4, 0xc3, 0x82,
	0x90, 0x31, 0xa0, 0xcf, 0x7c, 0x13, 0xec, 0xc1, 0x06, 0x98, 0xd3, 0x5d, 0x4b, 0x72, 0x4b, 0x71,
	0x24, 0x9f, 0xec, 0x4d, 0x49, 0x4e, 0x77, 0x2d, 0xc9, 0xef, 0x66, 0x1d, 0x90, 0x83, 0xf7, 0xc2,
	0x62, 0xdb, 0x12, 0x36, 0x71, 0x9f, 0x6e, 0xe0, 0xb6, 0x78, 0xc4, 0x8f, 0xeb, 0x37, 0xdc, 0x0f,
	0x0f, 0xdb, 0x72, 0x75, 0x43, 0xa7, 0x5f, 0x03, 0x72, 0x4f, 0x97, 0x79, 0xbb, 0xed, 0x69, 0xaf,
	0x5a, 0xf6, 0x59, 0xf5, 0x84, 0xb3, 0xe0, 0xf3, 0xf3, 0x5c, 0x60, 0xb1, 0x98, 0xd1, 0x54, 0x4b,
	0x66, 0xca, 0x95, 0x95, 0x1c, 0x45, 0x3a, 0xe7, 0x33, 0xcb, 0xbc, 0x98, 0x1b, 0x61, 0xff, 0x81,
	0xbd, 0x04, 0x2c, 0xbe, 0x77, 0xf6, 0x46, 0xde, 0x7c, 0x74, 0xc9, 0xfc, 0xc7, 0xc5, 0xfd, 0xf9,
	0x08, 0x8b, 0x73, 0x7f, 0x3f, 0xbb, 0x5d, 0x7f, 0xf3, 0xb3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x71, 0x29, 0xe7, 0xe4, 0x1a, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NodeClient is the client API for Node service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeClient interface {
	GetSyncStatus(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SyncStatus, error)
	GetGenesis(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Genesis, error)
	GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Version, error)
	ListImplementedServices(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ImplementedServices, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) GetSyncStatus(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SyncStatus, error) {
	out := new(SyncStatus)
	err := c.cc.Invoke(ctx, "/ethereum.eth.v1alpha1.Node/GetSyncStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) GetGenesis(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Genesis, error) {
	out := new(Genesis)
	err := c.cc.Invoke(ctx, "/ethereum.eth.v1alpha1.Node/GetGenesis", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Version, error) {
	out := new(Version)
	err := c.cc.Invoke(ctx, "/ethereum.eth.v1alpha1.Node/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) ListImplementedServices(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ImplementedServices, error) {
	out := new(ImplementedServices)
	err := c.cc.Invoke(ctx, "/ethereum.eth.v1alpha1.Node/ListImplementedServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServer is the server API for Node service.
type NodeServer interface {
	GetSyncStatus(context.Context, *empty.Empty) (*SyncStatus, error)
	GetGenesis(context.Context, *empty.Empty) (*Genesis, error)
	GetVersion(context.Context, *empty.Empty) (*Version, error)
	ListImplementedServices(context.Context, *empty.Empty) (*ImplementedServices, error)
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_GetSyncStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).GetSyncStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ethereum.eth.v1alpha1.Node/GetSyncStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).GetSyncStatus(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_GetGenesis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).GetGenesis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ethereum.eth.v1alpha1.Node/GetGenesis",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).GetGenesis(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ethereum.eth.v1alpha1.Node/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).GetVersion(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_ListImplementedServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).ListImplementedServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ethereum.eth.v1alpha1.Node/ListImplementedServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).ListImplementedServices(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ethereum.eth.v1alpha1.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSyncStatus",
			Handler:    _Node_GetSyncStatus_Handler,
		},
		{
			MethodName: "GetGenesis",
			Handler:    _Node_GetGenesis_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _Node_GetVersion_Handler,
		},
		{
			MethodName: "ListImplementedServices",
			Handler:    _Node_ListImplementedServices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eth/v1alpha1/node.proto",
}
