// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eth/v1alpha1/validator.proto

package eth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ValidatorStatus int32

const (
	ValidatorStatus_UNKNOWN_STATUS ValidatorStatus = 0
	ValidatorStatus_DEPOSITED      ValidatorStatus = 1
	ValidatorStatus_PENDING        ValidatorStatus = 2
	ValidatorStatus_ACTIVE         ValidatorStatus = 3
	ValidatorStatus_EXITING        ValidatorStatus = 4
	ValidatorStatus_SLASHING       ValidatorStatus = 5
	ValidatorStatus_EXITED         ValidatorStatus = 6
)

var ValidatorStatus_name = map[int32]string{
	0: "UNKNOWN_STATUS",
	1: "DEPOSITED",
	2: "PENDING",
	3: "ACTIVE",
	4: "EXITING",
	5: "SLASHING",
	6: "EXITED",
}

var ValidatorStatus_value = map[string]int32{
	"UNKNOWN_STATUS": 0,
	"DEPOSITED":      1,
	"PENDING":        2,
	"ACTIVE":         3,
	"EXITING":        4,
	"SLASHING":       5,
	"EXITED":         6,
}

func (x ValidatorStatus) String() string {
	return proto.EnumName(ValidatorStatus_name, int32(x))
}

func (ValidatorStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f8ef4b6a7db76675, []int{0}
}

type DomainRequest struct {
	Epoch                uint64   `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Domain               []byte   `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DomainRequest) Reset()         { *m = DomainRequest{} }
func (m *DomainRequest) String() string { return proto.CompactTextString(m) }
func (*DomainRequest) ProtoMessage()    {}
func (*DomainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef4b6a7db76675, []int{0}
}

func (m *DomainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DomainRequest.Unmarshal(m, b)
}
func (m *DomainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DomainRequest.Marshal(b, m, deterministic)
}
func (m *DomainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomainRequest.Merge(m, src)
}
func (m *DomainRequest) XXX_Size() int {
	return xxx_messageInfo_DomainRequest.Size(m)
}
func (m *DomainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DomainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DomainRequest proto.InternalMessageInfo

func (m *DomainRequest) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *DomainRequest) GetDomain() []byte {
	if m != nil {
		return m.Domain
	}
	return nil
}

type DomainResponse struct {
	SignatureDomain      []byte   `protobuf:"bytes,1,opt,name=signature_domain,json=signatureDomain,proto3" json:"signature_domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DomainResponse) Reset()         { *m = DomainResponse{} }
func (m *DomainResponse) String() string { return proto.CompactTextString(m) }
func (*DomainResponse) ProtoMessage()    {}
func (*DomainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef4b6a7db76675, []int{1}
}

func (m *DomainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DomainResponse.Unmarshal(m, b)
}
func (m *DomainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DomainResponse.Marshal(b, m, deterministic)
}
func (m *DomainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomainResponse.Merge(m, src)
}
func (m *DomainResponse) XXX_Size() int {
	return xxx_messageInfo_DomainResponse.Size(m)
}
func (m *DomainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DomainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DomainResponse proto.InternalMessageInfo

func (m *DomainResponse) GetSignatureDomain() []byte {
	if m != nil {
		return m.SignatureDomain
	}
	return nil
}

type ValidatorActivationRequest struct {
	PublicKeys           [][]byte `protobuf:"bytes,1,rep,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidatorActivationRequest) Reset()         { *m = ValidatorActivationRequest{} }
func (m *ValidatorActivationRequest) String() string { return proto.CompactTextString(m) }
func (*ValidatorActivationRequest) ProtoMessage()    {}
func (*ValidatorActivationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef4b6a7db76675, []int{2}
}

func (m *ValidatorActivationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorActivationRequest.Unmarshal(m, b)
}
func (m *ValidatorActivationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorActivationRequest.Marshal(b, m, deterministic)
}
func (m *ValidatorActivationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorActivationRequest.Merge(m, src)
}
func (m *ValidatorActivationRequest) XXX_Size() int {
	return xxx_messageInfo_ValidatorActivationRequest.Size(m)
}
func (m *ValidatorActivationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorActivationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorActivationRequest proto.InternalMessageInfo

func (m *ValidatorActivationRequest) GetPublicKeys() [][]byte {
	if m != nil {
		return m.PublicKeys
	}
	return nil
}

type ValidatorActivationResponse struct {
	Statuses             []*ValidatorActivationResponse_Status `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *ValidatorActivationResponse) Reset()         { *m = ValidatorActivationResponse{} }
func (m *ValidatorActivationResponse) String() string { return proto.CompactTextString(m) }
func (*ValidatorActivationResponse) ProtoMessage()    {}
func (*ValidatorActivationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef4b6a7db76675, []int{3}
}

func (m *ValidatorActivationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorActivationResponse.Unmarshal(m, b)
}
func (m *ValidatorActivationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorActivationResponse.Marshal(b, m, deterministic)
}
func (m *ValidatorActivationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorActivationResponse.Merge(m, src)
}
func (m *ValidatorActivationResponse) XXX_Size() int {
	return xxx_messageInfo_ValidatorActivationResponse.Size(m)
}
func (m *ValidatorActivationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorActivationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorActivationResponse proto.InternalMessageInfo

func (m *ValidatorActivationResponse) GetStatuses() []*ValidatorActivationResponse_Status {
	if m != nil {
		return m.Statuses
	}
	return nil
}

type ValidatorActivationResponse_Status struct {
	PublicKey            []byte                   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Status               *ValidatorStatusResponse `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ValidatorActivationResponse_Status) Reset()         { *m = ValidatorActivationResponse_Status{} }
func (m *ValidatorActivationResponse_Status) String() string { return proto.CompactTextString(m) }
func (*ValidatorActivationResponse_Status) ProtoMessage()    {}
func (*ValidatorActivationResponse_Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef4b6a7db76675, []int{3, 0}
}

func (m *ValidatorActivationResponse_Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorActivationResponse_Status.Unmarshal(m, b)
}
func (m *ValidatorActivationResponse_Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorActivationResponse_Status.Marshal(b, m, deterministic)
}
func (m *ValidatorActivationResponse_Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorActivationResponse_Status.Merge(m, src)
}
func (m *ValidatorActivationResponse_Status) XXX_Size() int {
	return xxx_messageInfo_ValidatorActivationResponse_Status.Size(m)
}
func (m *ValidatorActivationResponse_Status) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorActivationResponse_Status.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorActivationResponse_Status proto.InternalMessageInfo

func (m *ValidatorActivationResponse_Status) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *ValidatorActivationResponse_Status) GetStatus() *ValidatorStatusResponse {
	if m != nil {
		return m.Status
	}
	return nil
}

// Deprecated: Do not use.
type ChainStartResponse struct {
	Started              bool     `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
	GenesisTime          uint64   `protobuf:"varint,2,opt,name=genesis_time,json=genesisTime,proto3" json:"genesis_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainStartResponse) Reset()         { *m = ChainStartResponse{} }
func (m *ChainStartResponse) String() string { return proto.CompactTextString(m) }
func (*ChainStartResponse) ProtoMessage()    {}
func (*ChainStartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef4b6a7db76675, []int{4}
}

func (m *ChainStartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainStartResponse.Unmarshal(m, b)
}
func (m *ChainStartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainStartResponse.Marshal(b, m, deterministic)
}
func (m *ChainStartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainStartResponse.Merge(m, src)
}
func (m *ChainStartResponse) XXX_Size() int {
	return xxx_messageInfo_ChainStartResponse.Size(m)
}
func (m *ChainStartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainStartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChainStartResponse proto.InternalMessageInfo

func (m *ChainStartResponse) GetStarted() bool {
	if m != nil {
		return m.Started
	}
	return false
}

func (m *ChainStartResponse) GetGenesisTime() uint64 {
	if m != nil {
		return m.GenesisTime
	}
	return 0
}

type SyncedResponse struct {
	Synced               bool     `protobuf:"varint,1,opt,name=synced,proto3" json:"synced,omitempty"`
	GenesisTime          uint64   `protobuf:"varint,2,opt,name=genesis_time,json=genesisTime,proto3" json:"genesis_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncedResponse) Reset()         { *m = SyncedResponse{} }
func (m *SyncedResponse) String() string { return proto.CompactTextString(m) }
func (*SyncedResponse) ProtoMessage()    {}
func (*SyncedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef4b6a7db76675, []int{5}
}

func (m *SyncedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncedResponse.Unmarshal(m, b)
}
func (m *SyncedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncedResponse.Marshal(b, m, deterministic)
}
func (m *SyncedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncedResponse.Merge(m, src)
}
func (m *SyncedResponse) XXX_Size() int {
	return xxx_messageInfo_SyncedResponse.Size(m)
}
func (m *SyncedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SyncedResponse proto.InternalMessageInfo

func (m *SyncedResponse) GetSynced() bool {
	if m != nil {
		return m.Synced
	}
	return false
}

func (m *SyncedResponse) GetGenesisTime() uint64 {
	if m != nil {
		return m.GenesisTime
	}
	return 0
}

type ValidatorIndexRequest struct {
	PublicKey            []byte   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidatorIndexRequest) Reset()         { *m = ValidatorIndexRequest{} }
func (m *ValidatorIndexRequest) String() string { return proto.CompactTextString(m) }
func (*ValidatorIndexRequest) ProtoMessage()    {}
func (*ValidatorIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef4b6a7db76675, []int{6}
}

func (m *ValidatorIndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorIndexRequest.Unmarshal(m, b)
}
func (m *ValidatorIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorIndexRequest.Marshal(b, m, deterministic)
}
func (m *ValidatorIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorIndexRequest.Merge(m, src)
}
func (m *ValidatorIndexRequest) XXX_Size() int {
	return xxx_messageInfo_ValidatorIndexRequest.Size(m)
}
func (m *ValidatorIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorIndexRequest proto.InternalMessageInfo

func (m *ValidatorIndexRequest) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type ValidatorIndexResponse struct {
	Index                uint64   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidatorIndexResponse) Reset()         { *m = ValidatorIndexResponse{} }
func (m *ValidatorIndexResponse) String() string { return proto.CompactTextString(m) }
func (*ValidatorIndexResponse) ProtoMessage()    {}
func (*ValidatorIndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef4b6a7db76675, []int{7}
}

func (m *ValidatorIndexResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorIndexResponse.Unmarshal(m, b)
}
func (m *ValidatorIndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorIndexResponse.Marshal(b, m, deterministic)
}
func (m *ValidatorIndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorIndexResponse.Merge(m, src)
}
func (m *ValidatorIndexResponse) XXX_Size() int {
	return xxx_messageInfo_ValidatorIndexResponse.Size(m)
}
func (m *ValidatorIndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorIndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorIndexResponse proto.InternalMessageInfo

func (m *ValidatorIndexResponse) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type ValidatorStatusRequest struct {
	PublicKey            []byte   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidatorStatusRequest) Reset()         { *m = ValidatorStatusRequest{} }
func (m *ValidatorStatusRequest) String() string { return proto.CompactTextString(m) }
func (*ValidatorStatusRequest) ProtoMessage()    {}
func (*ValidatorStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef4b6a7db76675, []int{8}
}

func (m *ValidatorStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorStatusRequest.Unmarshal(m, b)
}
func (m *ValidatorStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorStatusRequest.Marshal(b, m, deterministic)
}
func (m *ValidatorStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorStatusRequest.Merge(m, src)
}
func (m *ValidatorStatusRequest) XXX_Size() int {
	return xxx_messageInfo_ValidatorStatusRequest.Size(m)
}
func (m *ValidatorStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorStatusRequest proto.InternalMessageInfo

func (m *ValidatorStatusRequest) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type ValidatorStatusResponse struct {
	Status                    ValidatorStatus `protobuf:"varint,1,opt,name=status,proto3,enum=ethereum.eth.v1alpha1.ValidatorStatus" json:"status,omitempty"`
	Eth1DepositBlockNumber    uint64          `protobuf:"varint,2,opt,name=eth1_deposit_block_number,json=eth1DepositBlockNumber,proto3" json:"eth1_deposit_block_number,omitempty"`
	DepositInclusionSlot      int64           `protobuf:"varint,3,opt,name=deposit_inclusion_slot,json=depositInclusionSlot,proto3" json:"deposit_inclusion_slot,omitempty"`
	ActivationEpoch           int64           `protobuf:"varint,4,opt,name=activation_epoch,json=activationEpoch,proto3" json:"activation_epoch,omitempty"`
	PositionInActivationQueue int64           `protobuf:"varint,5,opt,name=position_in_activation_queue,json=positionInActivationQueue,proto3" json:"position_in_activation_queue,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}        `json:"-"`
	XXX_unrecognized          []byte          `json:"-"`
	XXX_sizecache             int32           `json:"-"`
}

func (m *ValidatorStatusResponse) Reset()         { *m = ValidatorStatusResponse{} }
func (m *ValidatorStatusResponse) String() string { return proto.CompactTextString(m) }
func (*ValidatorStatusResponse) ProtoMessage()    {}
func (*ValidatorStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef4b6a7db76675, []int{9}
}

func (m *ValidatorStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorStatusResponse.Unmarshal(m, b)
}
func (m *ValidatorStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorStatusResponse.Marshal(b, m, deterministic)
}
func (m *ValidatorStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorStatusResponse.Merge(m, src)
}
func (m *ValidatorStatusResponse) XXX_Size() int {
	return xxx_messageInfo_ValidatorStatusResponse.Size(m)
}
func (m *ValidatorStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorStatusResponse proto.InternalMessageInfo

func (m *ValidatorStatusResponse) GetStatus() ValidatorStatus {
	if m != nil {
		return m.Status
	}
	return ValidatorStatus_UNKNOWN_STATUS
}

func (m *ValidatorStatusResponse) GetEth1DepositBlockNumber() uint64 {
	if m != nil {
		return m.Eth1DepositBlockNumber
	}
	return 0
}

func (m *ValidatorStatusResponse) GetDepositInclusionSlot() int64 {
	if m != nil {
		return m.DepositInclusionSlot
	}
	return 0
}

func (m *ValidatorStatusResponse) GetActivationEpoch() int64 {
	if m != nil {
		return m.ActivationEpoch
	}
	return 0
}

func (m *ValidatorStatusResponse) GetPositionInActivationQueue() int64 {
	if m != nil {
		return m.PositionInActivationQueue
	}
	return 0
}

type DutiesRequest struct {
	Epoch                uint64   `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	PublicKeys           [][]byte `protobuf:"bytes,2,rep,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DutiesRequest) Reset()         { *m = DutiesRequest{} }
func (m *DutiesRequest) String() string { return proto.CompactTextString(m) }
func (*DutiesRequest) ProtoMessage()    {}
func (*DutiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef4b6a7db76675, []int{10}
}

func (m *DutiesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DutiesRequest.Unmarshal(m, b)
}
func (m *DutiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DutiesRequest.Marshal(b, m, deterministic)
}
func (m *DutiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DutiesRequest.Merge(m, src)
}
func (m *DutiesRequest) XXX_Size() int {
	return xxx_messageInfo_DutiesRequest.Size(m)
}
func (m *DutiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DutiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DutiesRequest proto.InternalMessageInfo

func (m *DutiesRequest) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *DutiesRequest) GetPublicKeys() [][]byte {
	if m != nil {
		return m.PublicKeys
	}
	return nil
}

type DutiesResponse struct {
	Duties               []*DutiesResponse_Duty `protobuf:"bytes,1,rep,name=duties,proto3" json:"duties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DutiesResponse) Reset()         { *m = DutiesResponse{} }
func (m *DutiesResponse) String() string { return proto.CompactTextString(m) }
func (*DutiesResponse) ProtoMessage()    {}
func (*DutiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef4b6a7db76675, []int{11}
}

func (m *DutiesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DutiesResponse.Unmarshal(m, b)
}
func (m *DutiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DutiesResponse.Marshal(b, m, deterministic)
}
func (m *DutiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DutiesResponse.Merge(m, src)
}
func (m *DutiesResponse) XXX_Size() int {
	return xxx_messageInfo_DutiesResponse.Size(m)
}
func (m *DutiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DutiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DutiesResponse proto.InternalMessageInfo

func (m *DutiesResponse) GetDuties() []*DutiesResponse_Duty {
	if m != nil {
		return m.Duties
	}
	return nil
}

type DutiesResponse_Duty struct {
	Committee            []uint64        `protobuf:"varint,1,rep,packed,name=committee,proto3" json:"committee,omitempty"`
	CommitteeIndex       uint64          `protobuf:"varint,2,opt,name=committee_index,json=committeeIndex,proto3" json:"committee_index,omitempty"`
	AttesterSlot         uint64          `protobuf:"varint,3,opt,name=attester_slot,json=attesterSlot,proto3" json:"attester_slot,omitempty"`
	ProposerSlots        []uint64        `protobuf:"varint,4,rep,packed,name=proposer_slots,json=proposerSlots,proto3" json:"proposer_slots,omitempty"`
	PublicKey            []byte          `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Status               ValidatorStatus `protobuf:"varint,6,opt,name=status,proto3,enum=ethereum.eth.v1alpha1.ValidatorStatus" json:"status,omitempty"`
	ValidatorIndex       uint64          `protobuf:"varint,7,opt,name=validator_index,json=validatorIndex,proto3" json:"validator_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DutiesResponse_Duty) Reset()         { *m = DutiesResponse_Duty{} }
func (m *DutiesResponse_Duty) String() string { return proto.CompactTextString(m) }
func (*DutiesResponse_Duty) ProtoMessage()    {}
func (*DutiesResponse_Duty) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef4b6a7db76675, []int{11, 0}
}

func (m *DutiesResponse_Duty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DutiesResponse_Duty.Unmarshal(m, b)
}
func (m *DutiesResponse_Duty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DutiesResponse_Duty.Marshal(b, m, deterministic)
}
func (m *DutiesResponse_Duty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DutiesResponse_Duty.Merge(m, src)
}
func (m *DutiesResponse_Duty) XXX_Size() int {
	return xxx_messageInfo_DutiesResponse_Duty.Size(m)
}
func (m *DutiesResponse_Duty) XXX_DiscardUnknown() {
	xxx_messageInfo_DutiesResponse_Duty.DiscardUnknown(m)
}

var xxx_messageInfo_DutiesResponse_Duty proto.InternalMessageInfo

func (m *DutiesResponse_Duty) GetCommittee() []uint64 {
	if m != nil {
		return m.Committee
	}
	return nil
}

func (m *DutiesResponse_Duty) GetCommitteeIndex() uint64 {
	if m != nil {
		return m.CommitteeIndex
	}
	return 0
}

func (m *DutiesResponse_Duty) GetAttesterSlot() uint64 {
	if m != nil {
		return m.AttesterSlot
	}
	return 0
}

func (m *DutiesResponse_Duty) GetProposerSlots() []uint64 {
	if m != nil {
		return m.ProposerSlots
	}
	return nil
}

func (m *DutiesResponse_Duty) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *DutiesResponse_Duty) GetStatus() ValidatorStatus {
	if m != nil {
		return m.Status
	}
	return ValidatorStatus_UNKNOWN_STATUS
}

func (m *DutiesResponse_Duty) GetValidatorIndex() uint64 {
	if m != nil {
		return m.ValidatorIndex
	}
	return 0
}

type BlockRequest struct {
	Slot                 uint64   `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	RandaoReveal         []byte   `protobuf:"bytes,2,opt,name=randao_reveal,json=randaoReveal,proto3" json:"randao_reveal,omitempty"`
	Graffiti             []byte   `protobuf:"bytes,3,opt,name=graffiti,proto3" json:"graffiti,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRequest) Reset()         { *m = BlockRequest{} }
func (m *BlockRequest) String() string { return proto.CompactTextString(m) }
func (*BlockRequest) ProtoMessage()    {}
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef4b6a7db76675, []int{12}
}

func (m *BlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRequest.Unmarshal(m, b)
}
func (m *BlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRequest.Marshal(b, m, deterministic)
}
func (m *BlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequest.Merge(m, src)
}
func (m *BlockRequest) XXX_Size() int {
	return xxx_messageInfo_BlockRequest.Size(m)
}
func (m *BlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequest proto.InternalMessageInfo

func (m *BlockRequest) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *BlockRequest) GetRandaoReveal() []byte {
	if m != nil {
		return m.RandaoReveal
	}
	return nil
}

func (m *BlockRequest) GetGraffiti() []byte {
	if m != nil {
		return m.Graffiti
	}
	return nil
}

type ProposeResponse struct {
	BlockRoot            []byte   `protobuf:"bytes,1,opt,name=block_root,json=blockRoot,proto3" json:"block_root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProposeResponse) Reset()         { *m = ProposeResponse{} }
func (m *ProposeResponse) String() string { return proto.CompactTextString(m) }
func (*ProposeResponse) ProtoMessage()    {}
func (*ProposeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef4b6a7db76675, []int{13}
}

func (m *ProposeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposeResponse.Unmarshal(m, b)
}
func (m *ProposeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposeResponse.Marshal(b, m, deterministic)
}
func (m *ProposeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposeResponse.Merge(m, src)
}
func (m *ProposeResponse) XXX_Size() int {
	return xxx_messageInfo_ProposeResponse.Size(m)
}
func (m *ProposeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProposeResponse proto.InternalMessageInfo

func (m *ProposeResponse) GetBlockRoot() []byte {
	if m != nil {
		return m.BlockRoot
	}
	return nil
}

type AttestationDataRequest struct {
	Slot                 uint64   `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	CommitteeIndex       uint64   `protobuf:"varint,2,opt,name=committee_index,json=committeeIndex,proto3" json:"committee_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttestationDataRequest) Reset()         { *m = AttestationDataRequest{} }
func (m *AttestationDataRequest) String() string { return proto.CompactTextString(m) }
func (*AttestationDataRequest) ProtoMessage()    {}
func (*AttestationDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef4b6a7db76675, []int{14}
}

func (m *AttestationDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttestationDataRequest.Unmarshal(m, b)
}
func (m *AttestationDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttestationDataRequest.Marshal(b, m, deterministic)
}
func (m *AttestationDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttestationDataRequest.Merge(m, src)
}
func (m *AttestationDataRequest) XXX_Size() int {
	return xxx_messageInfo_AttestationDataRequest.Size(m)
}
func (m *AttestationDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AttestationDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AttestationDataRequest proto.InternalMessageInfo

func (m *AttestationDataRequest) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *AttestationDataRequest) GetCommitteeIndex() uint64 {
	if m != nil {
		return m.CommitteeIndex
	}
	return 0
}

type AttestResponse struct {
	AttestationDataRoot  []byte   `protobuf:"bytes,1,opt,name=attestation_data_root,json=attestationDataRoot,proto3" json:"attestation_data_root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttestResponse) Reset()         { *m = AttestResponse{} }
func (m *AttestResponse) String() string { return proto.CompactTextString(m) }
func (*AttestResponse) ProtoMessage()    {}
func (*AttestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef4b6a7db76675, []int{15}
}

func (m *AttestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttestResponse.Unmarshal(m, b)
}
func (m *AttestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttestResponse.Marshal(b, m, deterministic)
}
func (m *AttestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttestResponse.Merge(m, src)
}
func (m *AttestResponse) XXX_Size() int {
	return xxx_messageInfo_AttestResponse.Size(m)
}
func (m *AttestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AttestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AttestResponse proto.InternalMessageInfo

func (m *AttestResponse) GetAttestationDataRoot() []byte {
	if m != nil {
		return m.AttestationDataRoot
	}
	return nil
}

type AggregateSelectionRequest struct {
	Slot                 uint64   `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	CommitteeIndex       uint64   `protobuf:"varint,2,opt,name=committee_index,json=committeeIndex,proto3" json:"committee_index,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	SlotSignature        []byte   `protobuf:"bytes,4,opt,name=slot_signature,json=slotSignature,proto3" json:"slot_signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AggregateSelectionRequest) Reset()         { *m = AggregateSelectionRequest{} }
func (m *AggregateSelectionRequest) String() string { return proto.CompactTextString(m) }
func (*AggregateSelectionRequest) ProtoMessage()    {}
func (*AggregateSelectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef4b6a7db76675, []int{16}
}

func (m *AggregateSelectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AggregateSelectionRequest.Unmarshal(m, b)
}
func (m *AggregateSelectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AggregateSelectionRequest.Marshal(b, m, deterministic)
}
func (m *AggregateSelectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregateSelectionRequest.Merge(m, src)
}
func (m *AggregateSelectionRequest) XXX_Size() int {
	return xxx_messageInfo_AggregateSelectionRequest.Size(m)
}
func (m *AggregateSelectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregateSelectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AggregateSelectionRequest proto.InternalMessageInfo

func (m *AggregateSelectionRequest) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *AggregateSelectionRequest) GetCommitteeIndex() uint64 {
	if m != nil {
		return m.CommitteeIndex
	}
	return 0
}

func (m *AggregateSelectionRequest) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *AggregateSelectionRequest) GetSlotSignature() []byte {
	if m != nil {
		return m.SlotSignature
	}
	return nil
}

type AggregateSelectionResponse struct {
	AggregateAndProof    *AggregateAttestationAndProof `protobuf:"bytes,1,opt,name=aggregate_and_proof,json=aggregateAndProof,proto3" json:"aggregate_and_proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *AggregateSelectionResponse) Reset()         { *m = AggregateSelectionResponse{} }
func (m *AggregateSelectionResponse) String() string { return proto.CompactTextString(m) }
func (*AggregateSelectionResponse) ProtoMessage()    {}
func (*AggregateSelectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef4b6a7db76675, []int{17}
}

func (m *AggregateSelectionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AggregateSelectionResponse.Unmarshal(m, b)
}
func (m *AggregateSelectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AggregateSelectionResponse.Marshal(b, m, deterministic)
}
func (m *AggregateSelectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregateSelectionResponse.Merge(m, src)
}
func (m *AggregateSelectionResponse) XXX_Size() int {
	return xxx_messageInfo_AggregateSelectionResponse.Size(m)
}
func (m *AggregateSelectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregateSelectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AggregateSelectionResponse proto.InternalMessageInfo

func (m *AggregateSelectionResponse) GetAggregateAndProof() *AggregateAttestationAndProof {
	if m != nil {
		return m.AggregateAndProof
	}
	return nil
}

type SignedAggregateSubmitRequest struct {
	SignedAggregateAndProof *SignedAggregateAttestationAndProof `protobuf:"bytes,1,opt,name=signed_aggregate_and_proof,json=signedAggregateAndProof,proto3" json:"signed_aggregate_and_proof,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                            `json:"-"`
	XXX_unrecognized        []byte                              `json:"-"`
	XXX_sizecache           int32                               `json:"-"`
}

func (m *SignedAggregateSubmitRequest) Reset()         { *m = SignedAggregateSubmitRequest{} }
func (m *SignedAggregateSubmitRequest) String() string { return proto.CompactTextString(m) }
func (*SignedAggregateSubmitRequest) ProtoMessage()    {}
func (*SignedAggregateSubmitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef4b6a7db76675, []int{18}
}

func (m *SignedAggregateSubmitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedAggregateSubmitRequest.Unmarshal(m, b)
}
func (m *SignedAggregateSubmitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedAggregateSubmitRequest.Marshal(b, m, deterministic)
}
func (m *SignedAggregateSubmitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedAggregateSubmitRequest.Merge(m, src)
}
func (m *SignedAggregateSubmitRequest) XXX_Size() int {
	return xxx_messageInfo_SignedAggregateSubmitRequest.Size(m)
}
func (m *SignedAggregateSubmitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedAggregateSubmitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignedAggregateSubmitRequest proto.InternalMessageInfo

func (m *SignedAggregateSubmitRequest) GetSignedAggregateAndProof() *SignedAggregateAttestationAndProof {
	if m != nil {
		return m.SignedAggregateAndProof
	}
	return nil
}

type SignedAggregateSubmitResponse struct {
	AttestationDataRoot  []byte   `protobuf:"bytes,1,opt,name=attestation_data_root,json=attestationDataRoot,proto3" json:"attestation_data_root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedAggregateSubmitResponse) Reset()         { *m = SignedAggregateSubmitResponse{} }
func (m *SignedAggregateSubmitResponse) String() string { return proto.CompactTextString(m) }
func (*SignedAggregateSubmitResponse) ProtoMessage()    {}
func (*SignedAggregateSubmitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef4b6a7db76675, []int{19}
}

func (m *SignedAggregateSubmitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedAggregateSubmitResponse.Unmarshal(m, b)
}
func (m *SignedAggregateSubmitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedAggregateSubmitResponse.Marshal(b, m, deterministic)
}
func (m *SignedAggregateSubmitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedAggregateSubmitResponse.Merge(m, src)
}
func (m *SignedAggregateSubmitResponse) XXX_Size() int {
	return xxx_messageInfo_SignedAggregateSubmitResponse.Size(m)
}
func (m *SignedAggregateSubmitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedAggregateSubmitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignedAggregateSubmitResponse proto.InternalMessageInfo

func (m *SignedAggregateSubmitResponse) GetAttestationDataRoot() []byte {
	if m != nil {
		return m.AttestationDataRoot
	}
	return nil
}

type CommitteeSubnetsSubscribeRequest struct {
	Slots                []uint64 `protobuf:"varint,1,rep,packed,name=slots,proto3" json:"slots,omitempty"`
	CommitteeIds         []uint64 `protobuf:"varint,2,rep,packed,name=committee_ids,json=committeeIds,proto3" json:"committee_ids,omitempty"`
	IsAggregator         []bool   `protobuf:"varint,3,rep,packed,name=is_aggregator,json=isAggregator,proto3" json:"is_aggregator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitteeSubnetsSubscribeRequest) Reset()         { *m = CommitteeSubnetsSubscribeRequest{} }
func (m *CommitteeSubnetsSubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*CommitteeSubnetsSubscribeRequest) ProtoMessage()    {}
func (*CommitteeSubnetsSubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef4b6a7db76675, []int{20}
}

func (m *CommitteeSubnetsSubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitteeSubnetsSubscribeRequest.Unmarshal(m, b)
}
func (m *CommitteeSubnetsSubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitteeSubnetsSubscribeRequest.Marshal(b, m, deterministic)
}
func (m *CommitteeSubnetsSubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitteeSubnetsSubscribeRequest.Merge(m, src)
}
func (m *CommitteeSubnetsSubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_CommitteeSubnetsSubscribeRequest.Size(m)
}
func (m *CommitteeSubnetsSubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitteeSubnetsSubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommitteeSubnetsSubscribeRequest proto.InternalMessageInfo

func (m *CommitteeSubnetsSubscribeRequest) GetSlots() []uint64 {
	if m != nil {
		return m.Slots
	}
	return nil
}

func (m *CommitteeSubnetsSubscribeRequest) GetCommitteeIds() []uint64 {
	if m != nil {
		return m.CommitteeIds
	}
	return nil
}

func (m *CommitteeSubnetsSubscribeRequest) GetIsAggregator() []bool {
	if m != nil {
		return m.IsAggregator
	}
	return nil
}

type Validator struct {
	PublicKey                  []byte   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	WithdrawalCredentials      []byte   `protobuf:"bytes,2,opt,name=withdrawal_credentials,json=withdrawalCredentials,proto3" json:"withdrawal_credentials,omitempty"`
	EffectiveBalance           uint64   `protobuf:"varint,3,opt,name=effective_balance,json=effectiveBalance,proto3" json:"effective_balance,omitempty"`
	Slashed                    bool     `protobuf:"varint,4,opt,name=slashed,proto3" json:"slashed,omitempty"`
	ActivationEligibilityEpoch uint64   `protobuf:"varint,5,opt,name=activation_eligibility_epoch,json=activationEligibilityEpoch,proto3" json:"activation_eligibility_epoch,omitempty"`
	ActivationEpoch            uint64   `protobuf:"varint,6,opt,name=activation_epoch,json=activationEpoch,proto3" json:"activation_epoch,omitempty"`
	ExitEpoch                  uint64   `protobuf:"varint,7,opt,name=exit_epoch,json=exitEpoch,proto3" json:"exit_epoch,omitempty"`
	WithdrawableEpoch          uint64   `protobuf:"varint,8,opt,name=withdrawable_epoch,json=withdrawableEpoch,proto3" json:"withdrawable_epoch,omitempty"`
	XXX_NoUnkeyedLiteral       struct{} `json:"-"`
	XXX_unrecognized           []byte   `json:"-"`
	XXX_sizecache              int32    `json:"-"`
}

func (m *Validator) Reset()         { *m = Validator{} }
func (m *Validator) String() string { return proto.CompactTextString(m) }
func (*Validator) ProtoMessage()    {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef4b6a7db76675, []int{21}
}

func (m *Validator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Validator.Unmarshal(m, b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
}
func (m *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(m, src)
}
func (m *Validator) XXX_Size() int {
	return xxx_messageInfo_Validator.Size(m)
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

func (m *Validator) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Validator) GetWithdrawalCredentials() []byte {
	if m != nil {
		return m.WithdrawalCredentials
	}
	return nil
}

func (m *Validator) GetEffectiveBalance() uint64 {
	if m != nil {
		return m.EffectiveBalance
	}
	return 0
}

func (m *Validator) GetSlashed() bool {
	if m != nil {
		return m.Slashed
	}
	return false
}

func (m *Validator) GetActivationEligibilityEpoch() uint64 {
	if m != nil {
		return m.ActivationEligibilityEpoch
	}
	return 0
}

func (m *Validator) GetActivationEpoch() uint64 {
	if m != nil {
		return m.ActivationEpoch
	}
	return 0
}

func (m *Validator) GetExitEpoch() uint64 {
	if m != nil {
		return m.ExitEpoch
	}
	return 0
}

func (m *Validator) GetWithdrawableEpoch() uint64 {
	if m != nil {
		return m.WithdrawableEpoch
	}
	return 0
}

type ValidatorParticipation struct {
	GlobalParticipationRate float32  `protobuf:"fixed32,1,opt,name=global_participation_rate,json=globalParticipationRate,proto3" json:"global_participation_rate,omitempty"`
	VotedEther              uint64   `protobuf:"varint,2,opt,name=voted_ether,json=votedEther,proto3" json:"voted_ether,omitempty"`
	EligibleEther           uint64   `protobuf:"varint,3,opt,name=eligible_ether,json=eligibleEther,proto3" json:"eligible_ether,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *ValidatorParticipation) Reset()         { *m = ValidatorParticipation{} }
func (m *ValidatorParticipation) String() string { return proto.CompactTextString(m) }
func (*ValidatorParticipation) ProtoMessage()    {}
func (*ValidatorParticipation) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef4b6a7db76675, []int{22}
}

func (m *ValidatorParticipation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorParticipation.Unmarshal(m, b)
}
func (m *ValidatorParticipation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorParticipation.Marshal(b, m, deterministic)
}
func (m *ValidatorParticipation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorParticipation.Merge(m, src)
}
func (m *ValidatorParticipation) XXX_Size() int {
	return xxx_messageInfo_ValidatorParticipation.Size(m)
}
func (m *ValidatorParticipation) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorParticipation.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorParticipation proto.InternalMessageInfo

func (m *ValidatorParticipation) GetGlobalParticipationRate() float32 {
	if m != nil {
		return m.GlobalParticipationRate
	}
	return 0
}

func (m *ValidatorParticipation) GetVotedEther() uint64 {
	if m != nil {
		return m.VotedEther
	}
	return 0
}

func (m *ValidatorParticipation) GetEligibleEther() uint64 {
	if m != nil {
		return m.EligibleEther
	}
	return 0
}

type ValidatorInfo struct {
	PublicKey            []byte          `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Index                uint64          `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Epoch                uint64          `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Status               ValidatorStatus `protobuf:"varint,4,opt,name=status,proto3,enum=ethereum.eth.v1alpha1.ValidatorStatus" json:"status,omitempty"`
	TransitionTimestamp  uint64          `protobuf:"varint,5,opt,name=transition_timestamp,json=transitionTimestamp,proto3" json:"transition_timestamp,omitempty"`
	Balance              uint64          `protobuf:"varint,6,opt,name=balance,proto3" json:"balance,omitempty"`
	EffectiveBalance     uint64          `protobuf:"varint,7,opt,name=effective_balance,json=effectiveBalance,proto3" json:"effective_balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ValidatorInfo) Reset()         { *m = ValidatorInfo{} }
func (m *ValidatorInfo) String() string { return proto.CompactTextString(m) }
func (*ValidatorInfo) ProtoMessage()    {}
func (*ValidatorInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ef4b6a7db76675, []int{23}
}

func (m *ValidatorInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorInfo.Unmarshal(m, b)
}
func (m *ValidatorInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorInfo.Marshal(b, m, deterministic)
}
func (m *ValidatorInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorInfo.Merge(m, src)
}
func (m *ValidatorInfo) XXX_Size() int {
	return xxx_messageInfo_ValidatorInfo.Size(m)
}
func (m *ValidatorInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorInfo proto.InternalMessageInfo

func (m *ValidatorInfo) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *ValidatorInfo) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ValidatorInfo) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *ValidatorInfo) GetStatus() ValidatorStatus {
	if m != nil {
		return m.Status
	}
	return ValidatorStatus_UNKNOWN_STATUS
}

func (m *ValidatorInfo) GetTransitionTimestamp() uint64 {
	if m != nil {
		return m.TransitionTimestamp
	}
	return 0
}

func (m *ValidatorInfo) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *ValidatorInfo) GetEffectiveBalance() uint64 {
	if m != nil {
		return m.EffectiveBalance
	}
	return 0
}

func init() {
	proto.RegisterEnum("ethereum.eth.v1alpha1.ValidatorStatus", ValidatorStatus_name, ValidatorStatus_value)
	proto.RegisterType((*DomainRequest)(nil), "ethereum.eth.v1alpha1.DomainRequest")
	proto.RegisterType((*DomainResponse)(nil), "ethereum.eth.v1alpha1.DomainResponse")
	proto.RegisterType((*ValidatorActivationRequest)(nil), "ethereum.eth.v1alpha1.ValidatorActivationRequest")
	proto.RegisterType((*ValidatorActivationResponse)(nil), "ethereum.eth.v1alpha1.ValidatorActivationResponse")
	proto.RegisterType((*ValidatorActivationResponse_Status)(nil), "ethereum.eth.v1alpha1.ValidatorActivationResponse.Status")
	proto.RegisterType((*ChainStartResponse)(nil), "ethereum.eth.v1alpha1.ChainStartResponse")
	proto.RegisterType((*SyncedResponse)(nil), "ethereum.eth.v1alpha1.SyncedResponse")
	proto.RegisterType((*ValidatorIndexRequest)(nil), "ethereum.eth.v1alpha1.ValidatorIndexRequest")
	proto.RegisterType((*ValidatorIndexResponse)(nil), "ethereum.eth.v1alpha1.ValidatorIndexResponse")
	proto.RegisterType((*ValidatorStatusRequest)(nil), "ethereum.eth.v1alpha1.ValidatorStatusRequest")
	proto.RegisterType((*ValidatorStatusResponse)(nil), "ethereum.eth.v1alpha1.ValidatorStatusResponse")
	proto.RegisterType((*DutiesRequest)(nil), "ethereum.eth.v1alpha1.DutiesRequest")
	proto.RegisterType((*DutiesResponse)(nil), "ethereum.eth.v1alpha1.DutiesResponse")
	proto.RegisterType((*DutiesResponse_Duty)(nil), "ethereum.eth.v1alpha1.DutiesResponse.Duty")
	proto.RegisterType((*BlockRequest)(nil), "ethereum.eth.v1alpha1.BlockRequest")
	proto.RegisterType((*ProposeResponse)(nil), "ethereum.eth.v1alpha1.ProposeResponse")
	proto.RegisterType((*AttestationDataRequest)(nil), "ethereum.eth.v1alpha1.AttestationDataRequest")
	proto.RegisterType((*AttestResponse)(nil), "ethereum.eth.v1alpha1.AttestResponse")
	proto.RegisterType((*AggregateSelectionRequest)(nil), "ethereum.eth.v1alpha1.AggregateSelectionRequest")
	proto.RegisterType((*AggregateSelectionResponse)(nil), "ethereum.eth.v1alpha1.AggregateSelectionResponse")
	proto.RegisterType((*SignedAggregateSubmitRequest)(nil), "ethereum.eth.v1alpha1.SignedAggregateSubmitRequest")
	proto.RegisterType((*SignedAggregateSubmitResponse)(nil), "ethereum.eth.v1alpha1.SignedAggregateSubmitResponse")
	proto.RegisterType((*CommitteeSubnetsSubscribeRequest)(nil), "ethereum.eth.v1alpha1.CommitteeSubnetsSubscribeRequest")
	proto.RegisterType((*Validator)(nil), "ethereum.eth.v1alpha1.Validator")
	proto.RegisterType((*ValidatorParticipation)(nil), "ethereum.eth.v1alpha1.ValidatorParticipation")
	proto.RegisterType((*ValidatorInfo)(nil), "ethereum.eth.v1alpha1.ValidatorInfo")
}

func init() { proto.RegisterFile("eth/v1alpha1/validator.proto", fileDescriptor_f8ef4b6a7db76675) }

var fileDescriptor_f8ef4b6a7db76675 = []byte{
	// 1947 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xcd, 0x6f, 0x1b, 0xc7,
	0x15, 0xcf, 0x52, 0x14, 0x2d, 0x3d, 0x51, 0x94, 0x3c, 0xb6, 0x64, 0x8a, 0x91, 0x6c, 0x65, 0x15,
	0xc5, 0xb2, 0x5d, 0x93, 0x92, 0xec, 0x26, 0x48, 0x82, 0xb4, 0x95, 0x4c, 0xda, 0x15, 0x5c, 0x28,
	0xea, 0x52, 0x72, 0x8a, 0x22, 0xc0, 0x62, 0xb8, 0x3b, 0x22, 0x07, 0x59, 0xee, 0x30, 0xbb, 0x43,
	0xd9, 0xea, 0xa5, 0x4d, 0x2e, 0xed, 0xa1, 0xe8, 0xa5, 0x69, 0x91, 0x43, 0x51, 0xa0, 0xd7, 0x5e,
	0x7c, 0xeb, 0xa5, 0xff, 0x41, 0xaf, 0xfd, 0x13, 0xda, 0xfe, 0x0f, 0x3d, 0x16, 0xf3, 0xb1, 0x1f,
	0xa4, 0xb8, 0x22, 0x15, 0xa3, 0x27, 0x72, 0xdf, 0xe7, 0x6f, 0xde, 0xbc, 0x79, 0x1f, 0xb0, 0x4a,
	0x78, 0xa7, 0x76, 0xb6, 0x83, 0xbd, 0x5e, 0x07, 0xef, 0xd4, 0xce, 0xb0, 0x47, 0x5d, 0xcc, 0x59,
	0x50, 0xed, 0x05, 0x8c, 0x33, 0xb4, 0x44, 0x78, 0x87, 0x04, 0xa4, 0xdf, 0xad, 0x12, 0xde, 0xa9,
	0x46, 0x62, 0x95, 0xd5, 0x36, 0x63, 0x6d, 0x8f, 0xd4, 0x70, 0x8f, 0xd6, 0xb0, 0xef, 0x33, 0x8e,
	0x39, 0x65, 0x7e, 0xa8, 0x94, 0x2a, 0x6f, 0x6b, 0xae, 0xfc, 0x6a, 0xf5, 0x4f, 0x6b, 0xa4, 0xdb,
	0xe3, 0xe7, 0x9a, 0x79, 0x67, 0xc0, 0x5f, 0x8b, 0x60, 0x87, 0xf9, 0x76, 0xcb, 0x63, 0xce, 0x17,
	0x5a, 0xe0, 0xf6, 0x80, 0x00, 0xe6, 0x9c, 0x84, 0xca, 0xbc, 0xe2, 0x9b, 0x9f, 0xc0, 0x7c, 0x9d,
	0x75, 0x31, 0xf5, 0x2d, 0xf2, 0x65, 0x9f, 0x84, 0x1c, 0xdd, 0x84, 0x69, 0xd2, 0x63, 0x4e, 0xa7,
	0x6c, 0xac, 0x1b, 0x5b, 0x79, 0x4b, 0x7d, 0xa0, 0x65, 0x28, 0xb8, 0x52, 0xac, 0x9c, 0x5b, 0x37,
	0xb6, 0x8a, 0x96, 0xfe, 0x32, 0x3f, 0x86, 0x52, 0xa4, 0x1e, 0xf6, 0x98, 0x1f, 0x12, 0x74, 0x0f,
	0x16, 0x43, 0xda, 0xf6, 0x31, 0xef, 0x07, 0xc4, 0xd6, 0x3a, 0x86, 0xd4, 0x59, 0x88, 0xe9, 0x4a,
	0xc5, 0xfc, 0x04, 0x2a, 0x2f, 0xa2, 0x08, 0xed, 0x39, 0x9c, 0x9e, 0x49, 0x60, 0x11, 0x90, 0x3b,
	0x30, 0xd7, 0xeb, 0xb7, 0x3c, 0xea, 0xd8, 0x5f, 0x90, 0xf3, 0xb0, 0x6c, 0xac, 0x4f, 0x6d, 0x15,
	0x2d, 0x50, 0xa4, 0xe7, 0xe4, 0x3c, 0x34, 0xff, 0x63, 0xc0, 0xdb, 0x23, 0xf5, 0x35, 0x92, 0x13,
	0x98, 0x11, 0x67, 0xed, 0x87, 0x44, 0x69, 0xcf, 0xed, 0x7e, 0x58, 0x1d, 0x79, 0x01, 0xd5, 0x4b,
	0xac, 0x54, 0x9b, 0xd2, 0x84, 0x15, 0x9b, 0xaa, 0x30, 0x28, 0x28, 0x1a, 0x5a, 0x03, 0x48, 0x10,
	0xea, 0x43, 0xce, 0xc6, 0x00, 0xd1, 0x53, 0x28, 0x28, 0x25, 0x19, 0xb3, 0xb9, 0xdd, 0xea, 0x38,
	0xef, 0xda, 0x95, 0xf6, 0x6c, 0x69, 0x6d, 0xf3, 0x04, 0xd0, 0x93, 0x0e, 0xa6, 0x7e, 0x93, 0xe3,
	0x80, 0xc7, 0xa7, 0x2b, 0xc3, 0xb5, 0x50, 0x10, 0x88, 0x2b, 0x3d, 0xcf, 0x58, 0xd1, 0x27, 0x7a,
	0x07, 0x8a, 0x6d, 0xe2, 0x93, 0x90, 0x86, 0x36, 0xa7, 0x5d, 0x22, 0xbd, 0xe7, 0xad, 0x39, 0x4d,
	0x3b, 0xa6, 0x5d, 0xf2, 0x51, 0xae, 0x6c, 0x98, 0xcf, 0xa1, 0xd4, 0x3c, 0xf7, 0x1d, 0xe2, 0xc6,
	0x26, 0x97, 0xa1, 0x10, 0x4a, 0x8a, 0xb6, 0xa8, 0xbf, 0x26, 0x30, 0x68, 0xbe, 0x0f, 0x4b, 0xf1,
	0x31, 0x0e, 0x7c, 0x97, 0xbc, 0x8a, 0x6e, 0xf1, 0xf2, 0x18, 0x99, 0x55, 0x58, 0x1e, 0xd6, 0xd3,
	0x60, 0x6e, 0xc2, 0x34, 0x15, 0x84, 0x28, 0x0f, 0xe5, 0x87, 0xf9, 0x41, 0x4a, 0x3e, 0x0a, 0xd7,
	0x44, 0x8e, 0xfe, 0x96, 0x83, 0x5b, 0x19, 0x81, 0x46, 0x3f, 0x88, 0x2f, 0x4a, 0xa8, 0x95, 0x76,
	0xdf, 0x9b, 0xf0, 0xa2, 0xb4, 0x16, 0xfa, 0x10, 0x56, 0x08, 0xef, 0xec, 0xd8, 0x2e, 0xe9, 0xb1,
	0x90, 0x72, 0xf5, 0xfe, 0x6c, 0xbf, 0xdf, 0x6d, 0x91, 0x40, 0x07, 0x6b, 0x59, 0x08, 0xd4, 0x15,
	0x7f, 0x5f, 0xb0, 0x0f, 0x25, 0x17, 0x3d, 0x86, 0xe5, 0x48, 0x8b, 0xfa, 0x8e, 0xd7, 0x0f, 0x29,
	0xf3, 0xed, 0xd0, 0x63, 0xbc, 0x3c, 0xb5, 0x6e, 0x6c, 0x4d, 0x59, 0x37, 0x35, 0xf7, 0x20, 0x62,
	0x36, 0x3d, 0xc6, 0xc5, 0x1b, 0xc3, 0x71, 0xa6, 0xda, 0xea, 0xb9, 0xe6, 0xa5, 0xfc, 0x42, 0x42,
	0x6f, 0xc8, 0x87, 0xfb, 0x43, 0x58, 0x95, 0x06, 0x84, 0x20, 0xf5, 0xed, 0x94, 0xda, 0x97, 0x7d,
	0xd2, 0x27, 0xe5, 0x69, 0xa9, 0xb6, 0x12, 0xc9, 0x1c, 0xf8, 0xc9, 0x13, 0xf8, 0xa9, 0x10, 0x30,
	0x9f, 0xc2, 0x7c, 0xbd, 0xcf, 0x29, 0x09, 0x2f, 0x2f, 0x10, 0x43, 0xaf, 0x35, 0x77, 0xe1, 0xb5,
	0xfe, 0x37, 0x07, 0xa5, 0xc8, 0x90, 0x8e, 0xfb, 0x3e, 0x14, 0x5c, 0x49, 0xd1, 0xcf, 0xf3, 0x7e,
	0x46, 0xdc, 0x07, 0xd5, 0xc4, 0xe7, 0xb9, 0xa5, 0x35, 0x2b, 0x7f, 0xc9, 0x41, 0x5e, 0x10, 0xd0,
	0x2a, 0xcc, 0x3a, 0xac, 0xdb, 0xa5, 0x9c, 0x13, 0x22, 0xed, 0xe5, 0xad, 0x84, 0x80, 0xee, 0xc2,
	0x42, 0xfc, 0x61, 0xab, 0xbc, 0x52, 0x17, 0x53, 0x8a, 0xc9, 0x32, 0xfd, 0xd0, 0x06, 0xcc, 0xab,
	0x22, 0x49, 0x82, 0xe4, 0x1e, 0xf2, 0x56, 0x31, 0x22, 0xca, 0xf8, 0x6f, 0x42, 0xa9, 0x17, 0xb0,
	0x1e, 0x0b, 0xb5, 0x50, 0x58, 0xce, 0x4b, 0x87, 0xf3, 0x11, 0x55, 0x48, 0x0d, 0xd7, 0x87, 0xe9,
	0xe1, 0xfa, 0x90, 0xa4, 0x5d, 0xe1, 0x3b, 0xa5, 0xdd, 0x5d, 0x58, 0x88, 0x1b, 0x8c, 0x3e, 0xd3,
	0x35, 0x75, 0xa6, 0xb3, 0x81, 0x27, 0x65, 0x3a, 0x50, 0x94, 0x39, 0x17, 0xdd, 0x20, 0x82, 0xbc,
	0x3c, 0x9a, 0xba, 0x40, 0xf9, 0x5f, 0x9c, 0x3b, 0xc0, 0xbe, 0x8b, 0x99, 0x1d, 0x90, 0x33, 0x82,
	0x3d, 0x5d, 0xe7, 0x8b, 0x8a, 0x68, 0x49, 0x1a, 0xaa, 0xc0, 0x4c, 0x3b, 0xc0, 0xa7, 0xa7, 0x94,
	0x53, 0x19, 0x97, 0xa2, 0x15, 0x7f, 0x9b, 0xdb, 0xb0, 0x70, 0xa4, 0x4e, 0x1f, 0xdf, 0xef, 0x1a,
	0x80, 0x7a, 0x0a, 0x01, 0xd3, 0xde, 0x8a, 0xd6, 0xac, 0xa4, 0x58, 0x8c, 0x71, 0xf3, 0x04, 0x96,
	0xf7, 0x92, 0x7e, 0x54, 0xc7, 0x1c, 0x5f, 0x06, 0x70, 0xd2, 0x1b, 0x34, 0xeb, 0x50, 0x52, 0x66,
	0x63, 0x1c, 0xbb, 0xb0, 0x94, 0x6a, 0x7c, 0xb6, 0x8b, 0x39, 0x4e, 0x43, 0xba, 0x81, 0x87, 0x50,
	0x08, 0x70, 0x7f, 0x36, 0x60, 0x65, 0xaf, 0xdd, 0x0e, 0x48, 0x1b, 0x73, 0xd2, 0x24, 0x1e, 0x71,
	0xd2, 0xbd, 0xe9, 0x4d, 0x00, 0x0e, 0xa5, 0xc5, 0xd4, 0x70, 0x5a, 0x6c, 0x42, 0x49, 0xd8, 0xb3,
	0xe3, 0x6e, 0x29, 0x9f, 0x76, 0xd1, 0x9a, 0x17, 0xd4, 0x66, 0x44, 0x34, 0xbf, 0x32, 0xa0, 0x32,
	0x0a, 0xa0, 0x3e, 0xb3, 0x03, 0x37, 0x70, 0xc4, 0xb5, 0xb1, 0xef, 0xda, 0xbd, 0x80, 0xb1, 0x53,
	0x09, 0x78, 0x6e, 0xf7, 0x51, 0x46, 0xa6, 0xc5, 0xf6, 0x52, 0xf7, 0xb2, 0xe7, 0xbb, 0x47, 0x42,
	0xd5, 0xba, 0x1e, 0xdb, 0x8b, 0x48, 0xe6, 0x1f, 0x0d, 0x58, 0x15, 0x88, 0x88, 0x9b, 0x20, 0xe9,
	0xb7, 0xba, 0x94, 0x47, 0x71, 0x3a, 0x83, 0x4a, 0x28, 0xf9, 0x76, 0x36, 0x98, 0xac, 0xa6, 0x3c,
	0x64, 0x78, 0x14, 0xa4, 0x5b, 0xe1, 0x90, 0x4c, 0x04, 0xac, 0x09, 0x6b, 0x19, 0xb8, 0xde, 0x20,
	0x25, 0xbe, 0x36, 0x60, 0xfd, 0x49, 0x74, 0x95, 0xcd, 0x7e, 0xcb, 0x27, 0x3c, 0x6c, 0xf6, 0x5b,
	0xa1, 0x13, 0xd0, 0x16, 0x49, 0x55, 0x47, 0x55, 0x11, 0x54, 0x09, 0x52, 0x1f, 0xe2, 0x75, 0xa5,
	0x72, 0xc3, 0x55, 0xf5, 0x31, 0x6f, 0x15, 0x93, 0xcc, 0x70, 0xa5, 0x10, 0x0d, 0xe3, 0x40, 0xb1,
	0xa0, 0x3c, 0xb5, 0x3e, 0xb5, 0x35, 0x63, 0x15, 0x69, 0xb8, 0x17, 0xd3, 0xcc, 0x7f, 0xe5, 0x60,
	0x36, 0x2e, 0x08, 0xe3, 0x26, 0x90, 0xef, 0xc3, 0xf2, 0x4b, 0xca, 0x3b, 0x6e, 0x80, 0x5f, 0x62,
	0xcf, 0x76, 0x02, 0xe2, 0x12, 0x9f, 0x53, 0xec, 0x85, 0xfa, 0x75, 0x2f, 0x25, 0xdc, 0x27, 0x09,
	0x13, 0x3d, 0x80, 0xeb, 0xe4, 0xf4, 0x54, 0x24, 0xd4, 0x19, 0xb1, 0x5b, 0xd8, 0xc3, 0xbe, 0x43,
	0x74, 0x1d, 0x5c, 0x8c, 0x19, 0xfb, 0x8a, 0x2e, 0xe7, 0x10, 0x0f, 0x87, 0x1d, 0xe2, 0xca, 0x3c,
	0x15, 0x73, 0x88, 0xfa, 0x44, 0x3f, 0x82, 0xd5, 0x74, 0x97, 0xf2, 0x68, 0x9b, 0xb6, 0xa8, 0x47,
	0xf9, 0xb9, 0xee, 0x58, 0xd3, 0xd2, 0x62, 0x25, 0xd5, 0xb1, 0x12, 0x11, 0xd5, 0xbc, 0x46, 0xf5,
	0xb9, 0x82, 0xd4, 0xba, 0xd0, 0xe7, 0xd6, 0x00, 0xc8, 0x2b, 0xca, 0xb5, 0x90, 0xaa, 0x83, 0xb3,
	0x82, 0xa2, 0xd8, 0x0f, 0x01, 0xc5, 0x67, 0x6d, 0x79, 0x44, 0x8b, 0xcd, 0x48, 0xb1, 0xeb, 0x69,
	0x8e, 0x14, 0x37, 0xff, 0x64, 0xa4, 0xe6, 0x8c, 0x23, 0x1c, 0x70, 0xea, 0xd0, 0x9e, 0xf4, 0x86,
	0x3e, 0x82, 0x95, 0xb6, 0xc7, 0x5a, 0xd8, 0xb3, 0x7b, 0x69, 0xba, 0x1d, 0x60, 0x4e, 0xe4, 0x0d,
	0xe4, 0xac, 0x5b, 0x4a, 0x60, 0x40, 0xcf, 0xc2, 0x9c, 0x88, 0x26, 0x79, 0xc6, 0x38, 0x71, 0x6d,
	0x99, 0xf1, 0xba, 0x3c, 0x80, 0x24, 0x35, 0x04, 0x45, 0xbc, 0x7d, 0x15, 0x27, 0x01, 0x51, 0xca,
	0xa8, 0xb0, 0xcf, 0x47, 0x54, 0x29, 0x66, 0x7e, 0x93, 0x83, 0xf9, 0xd4, 0xd8, 0x74, 0xca, 0xc6,
	0x25, 0x42, 0x3c, 0x4c, 0xe5, 0x52, 0xc3, 0x54, 0xd2, 0xc9, 0xa7, 0xd2, 0x9d, 0x3c, 0x69, 0x4b,
	0xf9, 0xef, 0xd4, 0x96, 0x76, 0xe0, 0x26, 0x0f, 0xb0, 0xaf, 0x67, 0x0e, 0x31, 0x30, 0x86, 0x1c,
	0x77, 0x7b, 0xfa, 0xba, 0x6f, 0x24, 0xbc, 0xe3, 0x88, 0x25, 0x72, 0x28, 0x4a, 0x33, 0x75, 0xbd,
	0xd1, 0xe7, 0xe8, 0x54, 0xbc, 0x36, 0x3a, 0x15, 0xef, 0x73, 0x58, 0x18, 0x02, 0x85, 0x10, 0x94,
	0x4e, 0x0e, 0x9f, 0x1f, 0x7e, 0xfa, 0xd9, 0xa1, 0xdd, 0x3c, 0xde, 0x3b, 0x3e, 0x69, 0x2e, 0xbe,
	0x85, 0xe6, 0x61, 0xb6, 0xde, 0x38, 0xfa, 0xb4, 0x79, 0x70, 0xdc, 0xa8, 0x2f, 0x1a, 0x68, 0x0e,
	0xae, 0x1d, 0x35, 0x0e, 0xeb, 0x07, 0x87, 0xcf, 0x16, 0x73, 0x08, 0xa0, 0xb0, 0xf7, 0xe4, 0xf8,
	0xe0, 0x45, 0x63, 0x71, 0x4a, 0x30, 0x1a, 0x3f, 0x3b, 0x38, 0x16, 0x8c, 0x3c, 0x2a, 0xc2, 0x4c,
	0xf3, 0x27, 0x7b, 0xcd, 0x1f, 0x8b, 0xaf, 0x69, 0x21, 0x26, 0x58, 0x8d, 0xfa, 0x62, 0x61, 0xf7,
	0x35, 0x82, 0x1b, 0xfb, 0x72, 0xf1, 0x3a, 0x64, 0x2e, 0x49, 0xde, 0xe6, 0xaf, 0x0c, 0x98, 0x7d,
	0x46, 0xb8, 0x1a, 0x5e, 0xd0, 0xbb, 0x63, 0x66, 0x1b, 0x59, 0x3d, 0x2a, 0x9b, 0x13, 0x4d, 0x40,
	0xe6, 0x7b, 0x5f, 0xff, 0xf3, 0xdf, 0xbf, 0xcf, 0xad, 0xa3, 0xdb, 0xb5, 0xd1, 0xeb, 0x66, 0x4d,
	0x0d, 0x47, 0x08, 0x43, 0xb1, 0xc9, 0x03, 0x82, 0xbb, 0xff, 0x0f, 0x10, 0x6f, 0x6d, 0x19, 0xdb,
	0x06, 0xfa, 0xca, 0x00, 0x50, 0xeb, 0x9c, 0xa8, 0x93, 0xd9, 0x1e, 0xd2, 0x3b, 0x66, 0xb6, 0x87,
	0x81, 0x55, 0x72, 0x82, 0x63, 0x4a, 0x79, 0xf4, 0x3b, 0x03, 0xae, 0x7f, 0x86, 0x29, 0x7f, 0xca,
	0x82, 0x64, 0x51, 0x42, 0xcb, 0x55, 0xb5, 0x38, 0x57, 0xa3, 0xc5, 0xb9, 0xda, 0x10, 0x8b, 0x73,
	0xe5, 0x5e, 0x86, 0xf3, 0x8b, 0x3b, 0x96, 0xf9, 0x58, 0x02, 0x78, 0x80, 0xee, 0x65, 0x01, 0x70,
	0x84, 0x8e, 0xdc, 0xbb, 0x6a, 0xa1, 0x0c, 0xf4, 0x6f, 0x72, 0x22, 0x28, 0xbf, 0x84, 0x79, 0x8d,
	0x47, 0x6d, 0x58, 0x99, 0x58, 0xb2, 0x02, 0x31, 0xb8, 0x98, 0x99, 0x0f, 0x25, 0x8e, 0xbb, 0x68,
	0x33, 0x0b, 0x87, 0x5a, 0xd4, 0x34, 0x86, 0x6d, 0x03, 0xbd, 0x4e, 0x22, 0x92, 0xcc, 0xf3, 0x68,
	0xe7, 0x2a, 0xeb, 0xaf, 0xba, 0xa9, 0xdd, 0xab, 0x6f, 0xcc, 0xe6, 0xce, 0xb8, 0xa8, 0x25, 0xb5,
	0x3b, 0x41, 0xfc, 0x8d, 0x01, 0xa5, 0xc1, 0x4d, 0x10, 0x7d, 0x6f, 0x9c, 0xef, 0xf4, 0xa2, 0x59,
	0x79, 0x38, 0xa1, 0xb4, 0x06, 0xb9, 0x29, 0x41, 0xde, 0x41, 0x6b, 0x59, 0x20, 0x55, 0x89, 0xfc,
	0xd6, 0xb8, 0x58, 0x53, 0x1e, 0x4e, 0xba, 0xc7, 0x2b, 0x60, 0x57, 0x5c, 0xfb, 0xc7, 0x67, 0xbd,
	0xae, 0xb3, 0xbf, 0x80, 0x99, 0x67, 0x44, 0x2d, 0x93, 0x68, 0x23, 0xc3, 0x47, 0x7a, 0xec, 0xaf,
	0x98, 0x59, 0x42, 0xb2, 0x78, 0x49, 0xd1, 0xf1, 0x61, 0x91, 0xe3, 0x3b, 0xfa, 0xb5, 0x01, 0x45,
	0x3d, 0xed, 0x2b, 0x00, 0x5b, 0x97, 0x0e, 0x71, 0x29, 0x0f, 0x95, 0xac, 0x76, 0x32, 0xb4, 0x3c,
	0x44, 0x48, 0xcc, 0x31, 0x48, 0xbe, 0x35, 0x00, 0x3d, 0x23, 0x7c, 0x68, 0x91, 0xc8, 0xbc, 0xa3,
	0xd1, 0x0b, 0x47, 0x26, 0xa8, 0x21, 0x71, 0xf3, 0x81, 0x04, 0xb5, 0x89, 0x36, 0x32, 0x53, 0x3b,
	0x51, 0x40, 0xbf, 0x35, 0x00, 0xe9, 0x53, 0xa5, 0xec, 0x20, 0x73, 0xbc, 0xaf, 0xcc, 0xba, 0x30,
	0xb8, 0xd8, 0x44, 0x70, 0xcc, 0x89, 0xe0, 0xbc, 0x36, 0x60, 0x4d, 0x4d, 0xc1, 0x17, 0xd7, 0x06,
	0x39, 0x35, 0xa3, 0xed, 0x71, 0x6b, 0xc1, 0xf0, 0x1e, 0x54, 0xd9, 0xb9, 0x82, 0x86, 0xc6, 0x7c,
	0x4f, 0x62, 0xde, 0x30, 0xdf, 0xc9, 0xc4, 0x1c, 0xe9, 0xa2, 0xbf, 0x1b, 0xb0, 0xa1, 0x10, 0x0f,
	0x0f, 0xf3, 0x83, 0xb8, 0x1f, 0x4d, 0xb6, 0x41, 0x0c, 0xac, 0x26, 0x95, 0xc7, 0x57, 0x53, 0xba,
	0x3a, 0xfa, 0x97, 0x30, 0xa7, 0x6f, 0xbf, 0xf1, 0x8a, 0x72, 0x74, 0xff, 0x52, 0x7f, 0x2f, 0x98,
	0xd7, 0xf7, 0x39, 0x0e, 0xce, 0x85, 0x6c, 0x25, 0xa3, 0x5d, 0x98, 0xef, 0x4a, 0xef, 0xb7, 0xcd,
	0xd5, 0x2c, 0xef, 0x62, 0xe0, 0x45, 0x62, 0x75, 0x8d, 0xf7, 0x92, 0xe1, 0x85, 0x05, 0x7d, 0x90,
	0xd5, 0xfe, 0xc6, 0x6c, 0x36, 0x99, 0xa0, 0xb6, 0x25, 0xa8, 0xfb, 0xe6, 0x56, 0x66, 0xbd, 0x92,
	0x06, 0xc5, 0x8f, 0x32, 0xb8, 0xff, 0x07, 0x03, 0x56, 0x58, 0xd0, 0x1e, 0x0d, 0x64, 0x3f, 0x69,
	0x03, 0x47, 0xc2, 0xd1, 0x91, 0xf1, 0xf3, 0xf7, 0xdb, 0x94, 0x77, 0xfa, 0xad, 0xaa, 0xc3, 0xba,
	0xb5, 0x5e, 0x70, 0x1e, 0x76, 0x31, 0xa7, 0x8e, 0x87, 0x5b, 0x61, 0x2d, 0xb2, 0x80, 0x7b, 0x34,
	0x1c, 0x70, 0xff, 0x31, 0xe1, 0x9d, 0xbf, 0xe6, 0x96, 0x1a, 0x91, 0x87, 0x46, 0xca, 0xc3, 0x3f,
	0x12, 0xfa, 0xe7, 0x0d, 0xde, 0xf9, 0x3c, 0xa2, 0xb7, 0x0a, 0xf2, 0x64, 0x8f, 0xfe, 0x17, 0x00,
	0x00, 0xff, 0xff, 0x26, 0x0e, 0x59, 0x14, 0xc5, 0x17, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BeaconNodeValidatorClient is the client API for BeaconNodeValidator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BeaconNodeValidatorClient interface {
	GetDuties(ctx context.Context, in *DutiesRequest, opts ...grpc.CallOption) (*DutiesResponse, error)
	StreamDuties(ctx context.Context, opts ...grpc.CallOption) (BeaconNodeValidator_StreamDutiesClient, error)
	DomainData(ctx context.Context, in *DomainRequest, opts ...grpc.CallOption) (*DomainResponse, error)
	WaitForChainStart(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (BeaconNodeValidator_WaitForChainStartClient, error)
	WaitForSynced(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (BeaconNodeValidator_WaitForSyncedClient, error)
	WaitForActivation(ctx context.Context, in *ValidatorActivationRequest, opts ...grpc.CallOption) (BeaconNodeValidator_WaitForActivationClient, error)
	ValidatorIndex(ctx context.Context, in *ValidatorIndexRequest, opts ...grpc.CallOption) (*ValidatorIndexResponse, error)
	ValidatorStatus(ctx context.Context, in *ValidatorStatusRequest, opts ...grpc.CallOption) (*ValidatorStatusResponse, error)
	GetBlock(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (*BeaconBlock, error)
	ProposeBlock(ctx context.Context, in *SignedBeaconBlock, opts ...grpc.CallOption) (*ProposeResponse, error)
	GetAttestationData(ctx context.Context, in *AttestationDataRequest, opts ...grpc.CallOption) (*AttestationData, error)
	ProposeAttestation(ctx context.Context, in *Attestation, opts ...grpc.CallOption) (*AttestResponse, error)
	SubmitAggregateSelectionProof(ctx context.Context, in *AggregateSelectionRequest, opts ...grpc.CallOption) (*AggregateSelectionResponse, error)
	SubmitSignedAggregateSelectionProof(ctx context.Context, in *SignedAggregateSubmitRequest, opts ...grpc.CallOption) (*SignedAggregateSubmitResponse, error)
	ProposeExit(ctx context.Context, in *SignedVoluntaryExit, opts ...grpc.CallOption) (*empty.Empty, error)
	SubscribeCommitteeSubnets(ctx context.Context, in *CommitteeSubnetsSubscribeRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type beaconNodeValidatorClient struct {
	cc *grpc.ClientConn
}

func NewBeaconNodeValidatorClient(cc *grpc.ClientConn) BeaconNodeValidatorClient {
	return &beaconNodeValidatorClient{cc}
}

func (c *beaconNodeValidatorClient) GetDuties(ctx context.Context, in *DutiesRequest, opts ...grpc.CallOption) (*DutiesResponse, error) {
	out := new(DutiesResponse)
	err := c.cc.Invoke(ctx, "/ethereum.eth.v1alpha1.BeaconNodeValidator/GetDuties", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconNodeValidatorClient) StreamDuties(ctx context.Context, opts ...grpc.CallOption) (BeaconNodeValidator_StreamDutiesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BeaconNodeValidator_serviceDesc.Streams[0], "/ethereum.eth.v1alpha1.BeaconNodeValidator/StreamDuties", opts...)
	if err != nil {
		return nil, err
	}
	x := &beaconNodeValidatorStreamDutiesClient{stream}
	return x, nil
}

type BeaconNodeValidator_StreamDutiesClient interface {
	Send(*DutiesRequest) error
	Recv() (*DutiesResponse, error)
	grpc.ClientStream
}

type beaconNodeValidatorStreamDutiesClient struct {
	grpc.ClientStream
}

func (x *beaconNodeValidatorStreamDutiesClient) Send(m *DutiesRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *beaconNodeValidatorStreamDutiesClient) Recv() (*DutiesResponse, error) {
	m := new(DutiesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *beaconNodeValidatorClient) DomainData(ctx context.Context, in *DomainRequest, opts ...grpc.CallOption) (*DomainResponse, error) {
	out := new(DomainResponse)
	err := c.cc.Invoke(ctx, "/ethereum.eth.v1alpha1.BeaconNodeValidator/DomainData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *beaconNodeValidatorClient) WaitForChainStart(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (BeaconNodeValidator_WaitForChainStartClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BeaconNodeValidator_serviceDesc.Streams[1], "/ethereum.eth.v1alpha1.BeaconNodeValidator/WaitForChainStart", opts...)
	if err != nil {
		return nil, err
	}
	x := &beaconNodeValidatorWaitForChainStartClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BeaconNodeValidator_WaitForChainStartClient interface {
	Recv() (*ChainStartResponse, error)
	grpc.ClientStream
}

type beaconNodeValidatorWaitForChainStartClient struct {
	grpc.ClientStream
}

func (x *beaconNodeValidatorWaitForChainStartClient) Recv() (*ChainStartResponse, error) {
	m := new(ChainStartResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *beaconNodeValidatorClient) WaitForSynced(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (BeaconNodeValidator_WaitForSyncedClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BeaconNodeValidator_serviceDesc.Streams[2], "/ethereum.eth.v1alpha1.BeaconNodeValidator/WaitForSynced", opts...)
	if err != nil {
		return nil, err
	}
	x := &beaconNodeValidatorWaitForSyncedClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BeaconNodeValidator_WaitForSyncedClient interface {
	Recv() (*SyncedResponse, error)
	grpc.ClientStream
}

type beaconNodeValidatorWaitForSyncedClient struct {
	grpc.ClientStream
}

func (x *beaconNodeValidatorWaitForSyncedClient) Recv() (*SyncedResponse, error) {
	m := new(SyncedResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *beaconNodeValidatorClient) WaitForActivation(ctx context.Context, in *ValidatorActivationRequest, opts ...grpc.CallOption) (BeaconNodeValidator_WaitForActivationClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BeaconNodeValidator_serviceDesc.Streams[3], "/ethereum.eth.v1alpha1.BeaconNodeValidator/WaitForActivation", opts...)
	if err != nil {
		return nil, err
	}
	x := &beaconNodeValidatorWaitForActivationClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BeaconNodeValidator_WaitForActivationClient interface {
	Recv() (*ValidatorActivationResponse, error)
	grpc.ClientStream
}

type beaconNodeValidatorWaitForActivationClient struct {
	grpc.ClientStream
}

func (x *beaconNodeValidatorWaitForActivationClient) Recv() (*ValidatorActivationResponse, error) {
	m := new(ValidatorActivationResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *beaconNodeValidatorClient) ValidatorIndex(ctx context.Context, in *ValidatorIndexRequest, opts ...grpc.CallOption) (*ValidatorIndexResponse, error) {
	out := new(ValidatorIndexResponse)
	err := c.cc.Invoke(ctx, "/ethereum.eth.v1alpha1.BeaconNodeValidator/ValidatorIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconNodeValidatorClient) ValidatorStatus(ctx context.Context, in *ValidatorStatusRequest, opts ...grpc.CallOption) (*ValidatorStatusResponse, error) {
	out := new(ValidatorStatusResponse)
	err := c.cc.Invoke(ctx, "/ethereum.eth.v1alpha1.BeaconNodeValidator/ValidatorStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconNodeValidatorClient) GetBlock(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (*BeaconBlock, error) {
	out := new(BeaconBlock)
	err := c.cc.Invoke(ctx, "/ethereum.eth.v1alpha1.BeaconNodeValidator/GetBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconNodeValidatorClient) ProposeBlock(ctx context.Context, in *SignedBeaconBlock, opts ...grpc.CallOption) (*ProposeResponse, error) {
	out := new(ProposeResponse)
	err := c.cc.Invoke(ctx, "/ethereum.eth.v1alpha1.BeaconNodeValidator/ProposeBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconNodeValidatorClient) GetAttestationData(ctx context.Context, in *AttestationDataRequest, opts ...grpc.CallOption) (*AttestationData, error) {
	out := new(AttestationData)
	err := c.cc.Invoke(ctx, "/ethereum.eth.v1alpha1.BeaconNodeValidator/GetAttestationData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconNodeValidatorClient) ProposeAttestation(ctx context.Context, in *Attestation, opts ...grpc.CallOption) (*AttestResponse, error) {
	out := new(AttestResponse)
	err := c.cc.Invoke(ctx, "/ethereum.eth.v1alpha1.BeaconNodeValidator/ProposeAttestation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconNodeValidatorClient) SubmitAggregateSelectionProof(ctx context.Context, in *AggregateSelectionRequest, opts ...grpc.CallOption) (*AggregateSelectionResponse, error) {
	out := new(AggregateSelectionResponse)
	err := c.cc.Invoke(ctx, "/ethereum.eth.v1alpha1.BeaconNodeValidator/SubmitAggregateSelectionProof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconNodeValidatorClient) SubmitSignedAggregateSelectionProof(ctx context.Context, in *SignedAggregateSubmitRequest, opts ...grpc.CallOption) (*SignedAggregateSubmitResponse, error) {
	out := new(SignedAggregateSubmitResponse)
	err := c.cc.Invoke(ctx, "/ethereum.eth.v1alpha1.BeaconNodeValidator/SubmitSignedAggregateSelectionProof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconNodeValidatorClient) ProposeExit(ctx context.Context, in *SignedVoluntaryExit, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/ethereum.eth.v1alpha1.BeaconNodeValidator/ProposeExit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconNodeValidatorClient) SubscribeCommitteeSubnets(ctx context.Context, in *CommitteeSubnetsSubscribeRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/ethereum.eth.v1alpha1.BeaconNodeValidator/SubscribeCommitteeSubnets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BeaconNodeValidatorServer is the server API for BeaconNodeValidator service.
type BeaconNodeValidatorServer interface {
	GetDuties(context.Context, *DutiesRequest) (*DutiesResponse, error)
	StreamDuties(BeaconNodeValidator_StreamDutiesServer) error
	DomainData(context.Context, *DomainRequest) (*DomainResponse, error)
	WaitForChainStart(*empty.Empty, BeaconNodeValidator_WaitForChainStartServer) error
	WaitForSynced(*empty.Empty, BeaconNodeValidator_WaitForSyncedServer) error
	WaitForActivation(*ValidatorActivationRequest, BeaconNodeValidator_WaitForActivationServer) error
	ValidatorIndex(context.Context, *ValidatorIndexRequest) (*ValidatorIndexResponse, error)
	ValidatorStatus(context.Context, *ValidatorStatusRequest) (*ValidatorStatusResponse, error)
	GetBlock(context.Context, *BlockRequest) (*BeaconBlock, error)
	ProposeBlock(context.Context, *SignedBeaconBlock) (*ProposeResponse, error)
	GetAttestationData(context.Context, *AttestationDataRequest) (*AttestationData, error)
	ProposeAttestation(context.Context, *Attestation) (*AttestResponse, error)
	SubmitAggregateSelectionProof(context.Context, *AggregateSelectionRequest) (*AggregateSelectionResponse, error)
	SubmitSignedAggregateSelectionProof(context.Context, *SignedAggregateSubmitRequest) (*SignedAggregateSubmitResponse, error)
	ProposeExit(context.Context, *SignedVoluntaryExit) (*empty.Empty, error)
	SubscribeCommitteeSubnets(context.Context, *CommitteeSubnetsSubscribeRequest) (*empty.Empty, error)
}

func RegisterBeaconNodeValidatorServer(s *grpc.Server, srv BeaconNodeValidatorServer) {
	s.RegisterService(&_BeaconNodeValidator_serviceDesc, srv)
}

func _BeaconNodeValidator_GetDuties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DutiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconNodeValidatorServer).GetDuties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ethereum.eth.v1alpha1.BeaconNodeValidator/GetDuties",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconNodeValidatorServer).GetDuties(ctx, req.(*DutiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconNodeValidator_StreamDuties_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BeaconNodeValidatorServer).StreamDuties(&beaconNodeValidatorStreamDutiesServer{stream})
}

type BeaconNodeValidator_StreamDutiesServer interface {
	Send(*DutiesResponse) error
	Recv() (*DutiesRequest, error)
	grpc.ServerStream
}

type beaconNodeValidatorStreamDutiesServer struct {
	grpc.ServerStream
}

func (x *beaconNodeValidatorStreamDutiesServer) Send(m *DutiesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *beaconNodeValidatorStreamDutiesServer) Recv() (*DutiesRequest, error) {
	m := new(DutiesRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _BeaconNodeValidator_DomainData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconNodeValidatorServer).DomainData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ethereum.eth.v1alpha1.BeaconNodeValidator/DomainData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconNodeValidatorServer).DomainData(ctx, req.(*DomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconNodeValidator_WaitForChainStart_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BeaconNodeValidatorServer).WaitForChainStart(m, &beaconNodeValidatorWaitForChainStartServer{stream})
}

type BeaconNodeValidator_WaitForChainStartServer interface {
	Send(*ChainStartResponse) error
	grpc.ServerStream
}

type beaconNodeValidatorWaitForChainStartServer struct {
	grpc.ServerStream
}

func (x *beaconNodeValidatorWaitForChainStartServer) Send(m *ChainStartResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _BeaconNodeValidator_WaitForSynced_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BeaconNodeValidatorServer).WaitForSynced(m, &beaconNodeValidatorWaitForSyncedServer{stream})
}

type BeaconNodeValidator_WaitForSyncedServer interface {
	Send(*SyncedResponse) error
	grpc.ServerStream
}

type beaconNodeValidatorWaitForSyncedServer struct {
	grpc.ServerStream
}

func (x *beaconNodeValidatorWaitForSyncedServer) Send(m *SyncedResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _BeaconNodeValidator_WaitForActivation_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ValidatorActivationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BeaconNodeValidatorServer).WaitForActivation(m, &beaconNodeValidatorWaitForActivationServer{stream})
}

type BeaconNodeValidator_WaitForActivationServer interface {
	Send(*ValidatorActivationResponse) error
	grpc.ServerStream
}

type beaconNodeValidatorWaitForActivationServer struct {
	grpc.ServerStream
}

func (x *beaconNodeValidatorWaitForActivationServer) Send(m *ValidatorActivationResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _BeaconNodeValidator_ValidatorIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidatorIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconNodeValidatorServer).ValidatorIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ethereum.eth.v1alpha1.BeaconNodeValidator/ValidatorIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconNodeValidatorServer).ValidatorIndex(ctx, req.(*ValidatorIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconNodeValidator_ValidatorStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidatorStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconNodeValidatorServer).ValidatorStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ethereum.eth.v1alpha1.BeaconNodeValidator/ValidatorStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconNodeValidatorServer).ValidatorStatus(ctx, req.(*ValidatorStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconNodeValidator_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconNodeValidatorServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ethereum.eth.v1alpha1.BeaconNodeValidator/GetBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconNodeValidatorServer).GetBlock(ctx, req.(*BlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconNodeValidator_ProposeBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedBeaconBlock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconNodeValidatorServer).ProposeBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ethereum.eth.v1alpha1.BeaconNodeValidator/ProposeBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconNodeValidatorServer).ProposeBlock(ctx, req.(*SignedBeaconBlock))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconNodeValidator_GetAttestationData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttestationDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconNodeValidatorServer).GetAttestationData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ethereum.eth.v1alpha1.BeaconNodeValidator/GetAttestationData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconNodeValidatorServer).GetAttestationData(ctx, req.(*AttestationDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconNodeValidator_ProposeAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Attestation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconNodeValidatorServer).ProposeAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ethereum.eth.v1alpha1.BeaconNodeValidator/ProposeAttestation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconNodeValidatorServer).ProposeAttestation(ctx, req.(*Attestation))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconNodeValidator_SubmitAggregateSelectionProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggregateSelectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconNodeValidatorServer).SubmitAggregateSelectionProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ethereum.eth.v1alpha1.BeaconNodeValidator/SubmitAggregateSelectionProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconNodeValidatorServer).SubmitAggregateSelectionProof(ctx, req.(*AggregateSelectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconNodeValidator_SubmitSignedAggregateSelectionProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedAggregateSubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconNodeValidatorServer).SubmitSignedAggregateSelectionProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ethereum.eth.v1alpha1.BeaconNodeValidator/SubmitSignedAggregateSelectionProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconNodeValidatorServer).SubmitSignedAggregateSelectionProof(ctx, req.(*SignedAggregateSubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconNodeValidator_ProposeExit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedVoluntaryExit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconNodeValidatorServer).ProposeExit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ethereum.eth.v1alpha1.BeaconNodeValidator/ProposeExit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconNodeValidatorServer).ProposeExit(ctx, req.(*SignedVoluntaryExit))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconNodeValidator_SubscribeCommitteeSubnets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitteeSubnetsSubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconNodeValidatorServer).SubscribeCommitteeSubnets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ethereum.eth.v1alpha1.BeaconNodeValidator/SubscribeCommitteeSubnets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconNodeValidatorServer).SubscribeCommitteeSubnets(ctx, req.(*CommitteeSubnetsSubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BeaconNodeValidator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ethereum.eth.v1alpha1.BeaconNodeValidator",
	HandlerType: (*BeaconNodeValidatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDuties",
			Handler:    _BeaconNodeValidator_GetDuties_Handler,
		},
		{
			MethodName: "DomainData",
			Handler:    _BeaconNodeValidator_DomainData_Handler,
		},
		{
			MethodName: "ValidatorIndex",
			Handler:    _BeaconNodeValidator_ValidatorIndex_Handler,
		},
		{
			MethodName: "ValidatorStatus",
			Handler:    _BeaconNodeValidator_ValidatorStatus_Handler,
		},
		{
			MethodName: "GetBlock",
			Handler:    _BeaconNodeValidator_GetBlock_Handler,
		},
		{
			MethodName: "ProposeBlock",
			Handler:    _BeaconNodeValidator_ProposeBlock_Handler,
		},
		{
			MethodName: "GetAttestationData",
			Handler:    _BeaconNodeValidator_GetAttestationData_Handler,
		},
		{
			MethodName: "ProposeAttestation",
			Handler:    _BeaconNodeValidator_ProposeAttestation_Handler,
		},
		{
			MethodName: "SubmitAggregateSelectionProof",
			Handler:    _BeaconNodeValidator_SubmitAggregateSelectionProof_Handler,
		},
		{
			MethodName: "SubmitSignedAggregateSelectionProof",
			Handler:    _BeaconNodeValidator_SubmitSignedAggregateSelectionProof_Handler,
		},
		{
			MethodName: "ProposeExit",
			Handler:    _BeaconNodeValidator_ProposeExit_Handler,
		},
		{
			MethodName: "SubscribeCommitteeSubnets",
			Handler:    _BeaconNodeValidator_SubscribeCommitteeSubnets_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamDuties",
			Handler:       _BeaconNodeValidator_StreamDuties_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "WaitForChainStart",
			Handler:       _BeaconNodeValidator_WaitForChainStart_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WaitForSynced",
			Handler:       _BeaconNodeValidator_WaitForSynced_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WaitForActivation",
			Handler:       _BeaconNodeValidator_WaitForActivation_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "eth/v1alpha1/validator.proto",
}
